[package]
name = "advent_of_code"
version = "1.0.0"
edition = "2021"

[[bin]]
name="server"
path="implementations/rust/src/main.rs"

[dependencies]
actix-web = "4"
serde = { version = "1.0.148", features = ["derive"] }